EST & Festival patches from Alan2009 at http://www.speech.cs.cmu.edu/15-492/homework/hw1/packed2009/ \n Festvox-2.4 and festlex_* still not merged

diff --git a/trunk/speech_tools/configure b/trunk/speech_tools/configure
--- a/trunk/speech_tools/configure
+++ b/trunk/speech_tools/configure
@@ -676,6 +676,7 @@ GREP
 EGREP
 TERMCAPLIB
 COMPILERTYPE
+LINUXAUDIO
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -4129,6 +4130,53 @@ fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
+LINUXAUDIO=none
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <alsa/version.h>
+int
+main ()
+{
+int j=
+                #if SND_LIB_SUBMINOR >= 14
+                3;
+                #endif
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  LINUXAUDIO="alsa"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+
 ac_config_files="$ac_config_files config/config"
 
 cat >confcache <<\_ACEOF
@@ -4822,11 +4870,12 @@ GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 TERMCAPLIB!$TERMCAPLIB$ac_delim
 COMPILERTYPE!$COMPILERTYPE$ac_delim
+LINUXAUDIO!$LINUXAUDIO$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 65; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 66; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
